# This is a basic workflow to help you get started with Actions

name: CD

# Controls when the action will run.
on:
  # Triggers the workflow on push to master events
  push:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.15.1]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://npm.pkg.github.com
          scope: avanssion

      - name: rm .npmrc, npm install, audit, lint, build
        run: |
          rm .npmrc
          npm ci
          # npm audit
          npm run lint:all
          npm run build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Run CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name lezine-frontend \
            --deployment-group-name lezine-frontend-group \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --github-location repository=$GITHUB_REPOSITORY,commitId=$GITHUB_SHA \
            --description "Deployment for commit $GITHUB_SHA." \

  ## Example of sending an automated message to Workplace after the workflow is run ##
  ## This could be any sort of messenger like Slack etc. ##
  # workplace:
  #   name: Workplace
  #   needs: deploy
  #   runs-on: ubuntu-latest
  #   if: always()
  #   steps:
  #     - name: Get conclusion via env.WORKFLOW_CONCLUSION
  #       uses: technote-space/workflow-conclusion-action@v2
  #     - name: Inject slug/short variables
  #       uses: rlespinasse/github-slug-action@v3.x
  #     - name: Set icon if job has succeeded
  #       if: env.WORKFLOW_CONCLUSION == 'success'
  #       run: |
  #         echo "STATUS_ICON=✅" >> $GITHUB_ENV
  #     - name: Set icon if job has failed
  #       if: env.WORKFLOW_CONCLUSION != 'success'
  #       run: |
  #         echo "STATUS_ICON=❌" >> $GITHUB_ENV
  #     - name: Notify
  #       run: |
  #         curl --location --request POST "https://graph.facebook.com/v6.0/me/messages?access_token=${{ SECRETS.WORKPLACE_CHAT_CI_CD_ACCESS_TOKEN }}" \
  #           --header "Content-Type: application/json" \
  #           --data-raw "{ \"recipient\": { \"thread_key\": \"${{ SECRETS.WORKPLACE_CHAT_CI_CD_THREAD_KEY }}\" }, \"message\": { \"text\": \"*${{ env.STATUS_ICON }} $GITHUB_WORKFLOW #$GITHUB_RUN_NUMBER\n*Repo* - $GITHUB_REPOSITORY\n\nhttps://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID\" } }"
